require_relative 'tasks/clean'
require_relative 'tasks/prepare'
require_relative 'tasks/build'
require_relative 'tasks/tag'
require_relative 'tasks/push'
require_relative 'tasks/publish'
require_relative 'tasks/provision'
require_relative 'tasks/destroy'
